package org.molgen.genomeCATPro.peaks;
/**
 * @name ExportFrequenciesDialog
 *
 * 
 * @author Katrin Tebel <tebel at molgen.mpg.de>
 * 
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. 
 * You can obtain a copy of the License at http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
import java.awt.Cursor;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.molgen.genomeCATPro.peaks.cnvcat.CNVCATFrame;
import org.openide.util.NbPreferences;

public class ExportFrequenciesDialog extends javax.swing.JDialog {

    int binsize = 500000;
    String filepath = "./test.txt";
    CNVCATFrame parent;

    /** Creates new form ExportFrequenciesDialog */
    public ExportFrequenciesDialog(java.awt.Frame parent, boolean modal, CNVCATFrame _parent) {
        super(parent, modal);
        initComponents();
        this.parent = _parent;
        this.jComboBoxResolution.setSelectedIndex(2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFilepath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxResolution = new javax.swing.JComboBox();
        jButtonExport = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.title")); // NOI18N

        jFilepath.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jFilepath.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jLabel2.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jLabel1.text")); // NOI18N

        jComboBoxResolution.setModel(new javax.swing.DefaultComboBoxModel(new Integer[] { 20,50,100,200,500 }));

        jButtonExport.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jButtonExport.text")); // NOI18N
        jButtonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportActionPerformed(evt);
            }
        });

        jButtonClose.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jButtonClose.text")); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12));
        jLabel3.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jLabel3.text")); // NOI18N

        jTextMsg.setFont(new java.awt.Font("Dialog", 3, 12));
        jTextMsg.setForeground(new java.awt.Color(255, 51, 153));
        jTextMsg.setText(org.openide.util.NbBundle.getMessage(ExportFrequenciesDialog.class, "ExportFrequenciesDialog.jTextMsg.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(jButtonExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxResolution, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextMsg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFilepath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxResolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jTextMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExport)
                    .addComponent(jButtonClose))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_jButtonCloseActionPerformed
    static public void ExportFrequencies(CNVCATFrame parent) {

        ExportFrequenciesDialog d = new ExportFrequenciesDialog(null, true, parent);
        d.setLocationRelativeTo(null);
        d.setVisible(true);

    }
private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportActionPerformed
    this.binsize = ((Integer) (this.jComboBoxResolution.getSelectedItem())).intValue() * 1000;
    this.filepath = this.jFilepath.getText();
    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    try {
        parent.writeFrequencies(this.binsize, this.filepath);
         this.jTextMsg.setText("done! ");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR!", JOptionPane.ERROR_MESSAGE);
         this.jTextMsg.setText("error-see logfile for more information");
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

// TODO add your handling code here:
}//GEN-LAST:event_jButtonExportActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String path = NbPreferences.forModule(ExportFrequenciesDialog.class).get("pathPreference", "");
    JFileChooser importFileChooser = new JFileChooser(path);
    importFileChooser.setSelectedFile(new File("exportFrequecies.txt"));

    int returnVal = importFileChooser.showSaveDialog(this);
    if (returnVal != JFileChooser.APPROVE_OPTION) {
        return;
    }

    this.jFilepath.setText(importFileChooser.getSelectedFile().getPath());

    Logger.getLogger(ExportFrequenciesDialog.class.getName()).log(Level.INFO,
            "You chose to export to: " +
            this.jFilepath.getText() );

    NbPreferences.forModule(ExportFrequenciesDialog.class).put("pathPreference", this.jFilepath.getText());// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JComboBox jComboBoxResolution;
    private javax.swing.JTextField jFilepath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jTextMsg;
    // End of variables declaration//GEN-END:variables
}
