package org.molgen.genomeCATPro.guimodul;

/**
 *
 * @author  tebel
 */
public class AboutBoxNeu extends javax.swing.JDialog {

    public static String vendorName = "<html>Max Planck Institut für molekulare Genetik<br/>" +
            "Dept. Human Molecular Genetics";
    public static String version;
    public static String imagePath = null;
    public static String appTitel;
    public static String edition;

    /** Creates new form AboutBox */
    public AboutBoxNeu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();

            this.textVendor.setText(vendorName);
            this.textVersion.setText(version);

            this.textEdition.setText(edition);
            this.textlAppTitel.setText(appTitel);


            this.textLizence.setText(
                    "<html> This application is subject to the terms of either the GNU <br/>" +
                    "General Public License Version 2 only (\"GPL\") or the <br/>Common" +
                    "Development and Distribution License(\"CDDL\") (collectively, the <br/>" +
                    "\"License\"). For more information please visit<br/> " +
                    "<href>http://www.netbeans.org/cddl-gplv2.html</href> or <br/>" +
                    " or nbbuild/licenses/CDDL-GPL-2-CP.<br/>" +
                    "This program is distributed in the hope that it will be useful,<br/>" +
                    " but WITHOUT ANY WARRANTY; without even the implied warranty of<br/> " +
                    "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</html>");

           
            pack();
        } catch (Exception e) {
            e.printStackTrace();
        }
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textlAppTitel = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelEdition = new javax.swing.JLabel();
        textEdition = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();
        textVersion = new javax.swing.JLabel();
        textVendor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLizence = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textlAppTitel.setFont(new java.awt.Font("Tahoma", 1, 18));
        textlAppTitel.setText("GenomeCATPro");

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/molgen/genomeCATPro/guimodul/MPIPic.jpg"))); // NOI18N
        labelImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEdition.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelEdition.setText("Edition:");

        textEdition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textEdition.setText("jLabel1");

        labelVersion.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelVersion.setText("Version:");
        labelVersion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        textVersion.setFont(new java.awt.Font("Tahoma", 0, 12));
        textVersion.setText("textVersion");

        textVendor.setFont(new java.awt.Font("Tahoma", 0, 12));
        textVendor.setText("Vendor");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Authors:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Reinhard Ullmann      ullmann[at]molgen.mpg.de");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Katrin Tebel            tebel[at]molgen.mpg.de");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelVersion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEdition, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(textVendor, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(textVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(textEdition, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdition)
                    .addComponent(textEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVersion)
                    .addComponent(textVersion))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textVendor)
                .addGap(56, 56, 56))
        );

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textLizence.setBackground(java.awt.SystemColor.control);
        textLizence.setContentType("text/html");
        textLizence.setEditable(false);
        jScrollPane1.setViewportView(textLizence);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(675, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textlAppTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGap(480, 480, 480)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textlAppTitel)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(171, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AboutBoxNeu dialog = new AboutBoxNeu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEdition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JLabel textEdition;
    private javax.swing.JEditorPane textLizence;
    private javax.swing.JLabel textVendor;
    private javax.swing.JLabel textVersion;
    private javax.swing.JLabel textlAppTitel;
    // End of variables declaration//GEN-END:variables
}
