/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.molgen.genomeCATPro.guimodul.XPort;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import org.molgen.genomeCATPro.guimodul.experiment.ExperimentDataView;

public final class ImportFileVisualPanel5 extends JPanel {

    /**
     * Creates new form ImportFileVisualPanel5
     */
    public ImportFileVisualPanel5() {
        initComponents();

    }

    public ExperimentDataView getExperimentDataView1() {
        return experimentDataView1;
    }

    public void setExperimentDataView1(ExperimentDataView experimentDataView1) {
        this.experimentDataView1 = experimentDataView1;
    }

    public JButton getJButtonImport() {
        return jButtonImport;
    }

    public void setJButtonImport(JButton jButtonImport) {
        this.jButtonImport = jButtonImport;
    }

    public JTextArea getJTextMsg() {
        return jTextMsg;
    }

    public void setJTextMsg(JTextArea jTextMsg) {
        this.jTextMsg = jTextMsg;
    }

    @Override
    public String getName() {
        return "Run Import";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCenter = new javax.swing.ButtonGroup();
        experimentDataView1 = new org.molgen.genomeCATPro.guimodul.experiment.ExperimentDataView(false);
        jButtonImport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMsg = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(850, 600));

        experimentDataView1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonImport.setBackground(new java.awt.Color(255, 51, 51));
        org.openide.awt.Mnemonics.setLocalizedText(jButtonImport, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel5.class, "ImportFileVisualPanel5.jButtonImport.text")); // NOI18N

        jTextMsg.setColumns(20);
        jTextMsg.setRows(5);
        jScrollPane1.setViewportView(jTextMsg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jButtonImport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(experimentDataView1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(460, Short.MAX_VALUE)
                .addComponent(jButtonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(experimentDataView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 146, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCenter;
    private org.molgen.genomeCATPro.guimodul.experiment.ExperimentDataView experimentDataView1;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextMsg;
    // End of variables declaration//GEN-END:variables
}
