/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.molgen.genomeCATPro.guimodul.XPort;

import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import org.molgen.genomeCATPro.datadb.service.DBUtils;

public final class ImportFileVisualPanel3 extends JPanel {

    /**
     * Creates new form ImportFileVisualPanel3
     */
    public ImportFileVisualPanel3() {
        initComponents();
    }

    public JTextField getFieldPlatform() {
        return fieldPlatform;
    }

    public void setFieldPlatform(JTextField fieldPlatform) {
        this.fieldPlatform = fieldPlatform;
    }

    public JTextField getFieldRelease() {
        return fieldRelease;
    }

    public void setFieldRelease(JTextField fieldRelease) {
        this.fieldRelease = fieldRelease;
    }

    public JTextField getFieldType() {
        return fieldType;
    }

    public void setFieldType(JTextField fieldType) {
        this.fieldType = fieldType;
    }

    public JButton getJButtonSelectMethod() {
        return jButtonSelectMethod;
    }

    public void setJButtonSelectMethod(JButton jButtonSelectMethod) {
        this.jButtonSelectMethod = jButtonSelectMethod;
    }

    public JButton getJButtonSelectPlatform() {
        return jButtonSelectPlatform;
    }

    public void setJButtonSelectPlatform(JButton jButtonSelectPlatform) {
        this.jButtonSelectPlatform = jButtonSelectPlatform;
    }

    public JButton getJButtonSelectRelease() {
        return jButtonSelectRelease;
    }

    public void setJButtonSelectRelease(JButton jButtonSelectRelease) {
        this.jButtonSelectRelease = jButtonSelectRelease;
    }

    public JButton getJButtonSelectType() {
        return jButtonSelectType;
    }

    public void setJButtonSelectType(JButton jButtonSelectType) {
        this.jButtonSelectType = jButtonSelectType;
    }

    public JComboBox getJComboBoxPlatformData() {
        return jComboBoxPlatformData;
    }

    public void setJComboBoxPlatformData(JComboBox jComboBoxPlatformData) {
        this.jComboBoxPlatformData = jComboBoxPlatformData;
    }

    public JTextField getFieldMethod() {
        return fieldMethod;
    }

    public void setFieldMethod(JTextField fieldMethod) {
        this.fieldMethod = fieldMethod;
    }

    public JTextPane getJTextFileInfo() {
        return jTextFileInfo;
    }

    public void setJTextFileInfo(JTextPane jTextFileInfo) {
        this.jTextFileInfo = jTextFileInfo;

    }

    @Override
    public String getName() {
        return "Select Platform";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCommArray = new javax.swing.JPanel();
        platform = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFileInfo = new javax.swing.JTextPane();
        fieldPlatform = new javax.swing.JTextField();
        jComboBoxPlatformData = new javax.swing.JComboBox();
        hintPlatform = new javax.swing.JLabel();
        platform_release = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        release = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        fieldRelease = new javax.swing.JTextField();
        fieldType = new javax.swing.JTextField();
        fieldMethod = new javax.swing.JTextField();
        jButtonSelectRelease = new javax.swing.JButton();
        jButtonSelectType = new javax.swing.JButton();
        jButtonSelectMethod = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSelectPlatform = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanelCommArray.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCommArray.setMaximumSize(new java.awt.Dimension(100, 1000));
        jPanelCommArray.setPreferredSize(new java.awt.Dimension(150, 400));

        platform.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(platform, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.platform.text")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jLabel1.text")); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextFileInfo.setContentType(org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jTextFileInfo.contentType")); // NOI18N
        jTextFileInfo.setEditable(false);
        jScrollPane1.setViewportView(jTextFileInfo);

        fieldPlatform.setText(org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.fieldPlatform.text")); // NOI18N

        hintPlatform.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        hintPlatform.setForeground(java.awt.Color.black);
        org.openide.awt.Mnemonics.setLocalizedText(hintPlatform, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.hintPlatform.text")); // NOI18N

        platform_release.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(platform_release, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.platform_release.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 11))); // NOI18N

        release.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(release, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.release.text")); // NOI18N

        type.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        type.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(type, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.type.text")); // NOI18N

        descriptionLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        descriptionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(descriptionLabel1, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.descriptionLabel1.text")); // NOI18N

        fieldRelease.setText(org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.fieldRelease.text")); // NOI18N

        fieldType.setToolTipText(org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.fieldType.toolTipText")); // NOI18N
        fieldType.setMaximumSize(new java.awt.Dimension(20, 100));
        fieldType.setMinimumSize(new java.awt.Dimension(4, 50));
        fieldType.setPreferredSize(new java.awt.Dimension(4, 50));

        fieldMethod.setMaximumSize(new java.awt.Dimension(20, 100));
        fieldMethod.setMinimumSize(new java.awt.Dimension(4, 50));
        fieldMethod.setPreferredSize(new java.awt.Dimension(4, 50));

        org.openide.awt.Mnemonics.setLocalizedText(jButtonSelectRelease, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jButtonSelectRelease.text")); // NOI18N
        jButtonSelectRelease.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonSelectRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectReleaseActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonSelectType, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jButtonSelectType.text")); // NOI18N
        jButtonSelectType.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jButtonSelectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectTypeActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonSelectMethod, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jButtonSelectMethod.text")); // NOI18N
        jButtonSelectMethod.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonSelectMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectMethodActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(release, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(type, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldMethod, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(fieldType, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(fieldRelease, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelectRelease)
                            .addComponent(jButtonSelectType)
                            .addComponent(jButtonSelectMethod))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonSelectMethod, jButtonSelectRelease, jButtonSelectType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fieldMethod, fieldRelease, fieldType});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(release)
                    .addComponent(fieldRelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectRelease))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type)
                    .addComponent(fieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectType, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(descriptionLabel1)
                    .addComponent(fieldMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fieldMethod, fieldRelease, fieldType, jButtonSelectMethod, jButtonSelectRelease, jButtonSelectType});

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonSelectPlatform, org.openide.util.NbBundle.getMessage(ImportFileVisualPanel3.class, "ImportFileVisualPanel3.jButtonSelectPlatform.text")); // NOI18N
        jButtonSelectPlatform.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout jPanelCommArrayLayout = new javax.swing.GroupLayout(jPanelCommArray);
        jPanelCommArray.setLayout(jPanelCommArrayLayout);
        jPanelCommArrayLayout.setHorizontalGroup(
            jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommArrayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392)
                .addComponent(jLabel1))
            .addGroup(jPanelCommArrayLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(platform, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(platform_release, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCommArrayLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(164, 164, 164))
                    .addGroup(jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fieldPlatform, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxPlatformData, javax.swing.GroupLayout.Alignment.LEADING, 0, 231, Short.MAX_VALUE)))
                .addComponent(jButtonSelectPlatform))
            .addGroup(jPanelCommArrayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelCommArrayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelCommArrayLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jScrollPane1});

        jPanelCommArrayLayout.setVerticalGroup(
            jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommArrayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hintPlatform)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommArrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(platform_release)
                    .addComponent(jComboBoxPlatformData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanelCommArrayLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fieldPlatform, jButtonSelectPlatform});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCommArray, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCommArray, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButtonSelectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectTypeActionPerformed

}//GEN-LAST:event_jButtonSelectTypeActionPerformed

private void jButtonSelectMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectMethodActionPerformed

}//GEN-LAST:event_jButtonSelectMethodActionPerformed

private void jButtonSelectReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectReleaseActionPerformed
    final JPanel panel = new JPanel();
    Vector<String> possibilities = DBUtils.getAllReleases();
    final JComboBox combo = new JComboBox(possibilities);
    combo.setEditable(true);
    panel.add(combo);
    if (JOptionPane.showConfirmDialog(null, panel,
            "choose release", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
        this.fieldRelease.setText((String) combo.getSelectedItem());
    }
}//GEN-LAST:event_jButtonSelectReleaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JTextField fieldMethod;
    private javax.swing.JTextField fieldPlatform;
    private javax.swing.JTextField fieldRelease;
    private javax.swing.JTextField fieldType;
    private javax.swing.JLabel hintPlatform;
    private javax.swing.JButton jButtonSelectMethod;
    private javax.swing.JButton jButtonSelectPlatform;
    private javax.swing.JButton jButtonSelectRelease;
    private javax.swing.JButton jButtonSelectType;
    private javax.swing.JComboBox jComboBoxPlatformData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCommArray;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextFileInfo;
    private javax.swing.JLabel platform;
    private javax.swing.JLabel platform_release;
    private javax.swing.JLabel release;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
