/*
 * Project2ExperimentDialog.java
 *
 * Created on August 5, 2011, 4:19 PM
 */
package org.molgen.genomeCATPro.guimodul.project;

import org.molgen.genomeCATPro.guimodul.experiment.*;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import org.molgen.genomeCATPro.data.DataManager;
import org.molgen.genomeCATPro.datadb.dbentities.ExperimentDetail;
import org.molgen.genomeCATPro.datadb.service.DBUtils;

/**
 *
 * @author  tebel
 */
public class Project2ExperimentDialog extends javax.swing.JDialog {

    ExperimentDetail experiment = null;

    /** Creates new form Project2ExperimentDialog */
    public Project2ExperimentDialog(java.awt.Frame parent, boolean modal, ExperimentDetail d) {
        super(parent, modal);
        this.experiment = d;


        //newData.setGenomeRelease(Defaults.GenomeRelease.toRelease(data.getGenomeRelease()));


        this.experimentDetailView1 = new ExperimentDetailView(experiment, false);
        initComponents();



    }
    
     public static void addExperiment2Project(ExperimentDetail e) {
        
        Project2ExperimentDialog d = new Project2ExperimentDialog(null, true, e);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbProject = new javax.swing.JComboBox();
        experimentDetailView1 = experimentDetailView1;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(Project2ExperimentDialog.class, "Project2ExperimentDialog.title")); // NOI18N

        jButtonAdd.setText(org.openide.util.NbBundle.getMessage(Project2ExperimentDialog.class, "Project2ExperimentDialog.jButtonApplyl.text")); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setText(org.openide.util.NbBundle.getMessage(Project2ExperimentDialog.class, "Project2ExperimentDialog.jButtonCancel.text")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(Project2ExperimentDialog.class, "Project2ExperimentDialog.jLabel1.text")); // NOI18N

        cbProject.setModel(new javax.swing.DefaultComboBoxModel( DBUtils.getStudies()));

        experimentDetailView1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(Project2ExperimentDialog.class, "Project2ExperimentDialog.experimentDetailView1.border.title"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(experimentDetailView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProject, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(experimentDetailView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(Project2ExperimentDialog.class, "Project2ExperimentDialog.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    this.experiment = null;
    this.dispose();
// TODO add your handling code here:
}//GEN-LAST:event_jButtonCancelActionPerformed

private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
    try {
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if (this.cbProject.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "please choose project!");
            return;
        }
        DataManager.addExperiment2Project(this.cbProject.getSelectedItem().toString(), this.experiment);
        JOptionPane.showMessageDialog(this, "ok - experiment added ");
        this.experiment = null;
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "error  - see logfile for more information: ");
    }
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_jButtonAddActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbProject;
    private org.molgen.genomeCATPro.guimodul.experiment.ExperimentDetailView experimentDetailView1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
