package org.molgen.genomeCATPro.guimodul.platform;

/**
 * @name PlatformDetailView
 *
 *
 * @author Katrin Tebel <tebel at molgen.mpg.de>
 *
 *
 * The contents of this file are subject to the terms of either the GNU General
 * Public License Version 2 only ("GPL") or the Common Development and
 * Distribution License("CDDL") (collectively, the "License"). You may not use
 * this file except in compliance with the License. You can obtain a copy of the
 * License at http://www.netbeans.org/cddl-gplv2.html or
 * nbbuild/licenses/CDDL-GPL-2-CP. See the License for the specific language
 * governing permissions and limitations under the License. This program is
 * distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.
 */
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jdesktop.beansbinding.Converter;
import org.molgen.genomeCATPro.datadb.dbentities.PlatformDetail;
import org.molgen.genomeCATPro.datadb.service.DBUtils;
import org.molgen.genomeCATPro.guimodul.SwingUtils;

/**
 * 170513 kt type/method changed
 *
 */
public class PlatformDetailView extends javax.swing.JPanel {

    private PlatformDetail platform;
    boolean edit = false;

    /**
     * Creates new form BeanForm
     */
    public PlatformDetailView() {

        this.platform = new PlatformDetail();
        edit = true;

        initComponents();
        setAllFieldsEditable(edit);
        Logger.getLogger(PlatformDetailView.class.getName()).log(Level.INFO,
                "constructor called");
    }

    public PlatformDetailView(PlatformDetail p, boolean edit) {
        this.edit = edit;
        this.platform = p;

        initComponents();
        setAllFieldsEditable(edit);
        Logger.getLogger(PlatformDetailView.class.getName()).log(Level.INFO,
                "constructor called");
    }

    static void view(PlatformDetail p, boolean edit) {
        JDialog d = new JDialog();
        d.setLocationRelativeTo(null);

        PlatformDetailView v = new PlatformDetailView(p, edit);
        d.setTitle("platform detail view");
        d.add(v);
        d.pack();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }

    public PlatformDetail getPlatform() {
        return this.platform;
    }

    public void setPlatform(PlatformDetail p) {
        this.platform.copy(p);
    }

    public void setPlatform(PlatformDetail p, boolean edit) {
        this.platform.copy(p);
        this.edit = edit;
        setAllFieldsEditable(edit);
        this.repaint();
        Logger.getLogger(
                PlatformDetailView.class.getName()).log(Level.INFO,
                        "platform set to: " + p.toFullString() + " editable: "
                        + (this.edit ? "true" : "false"));

    }
    private Color backgroundForName = Color.WHITE;

    /**
     * Get the value of backgroundForName
     *
     * @return the value of backgroundForName
     */
    public Color getBackgroundForName() {
        return backgroundForName;
    }

    /**
     * Set the value of backgroundForName
     *
     * @param backgroundForName new value of backgroundForName
     */
    public void setBackgroundForName(Color backgroundForName) {
        this.backgroundForName = backgroundForName;
        this.nameField.setBackground(this.backgroundForName);
    }

    void setTypeSelectable(boolean b) {
        this.fieldType.setEditable(b);
        this.jButtonSelectType.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        name_req = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        modifiedField = new javax.swing.JTextField();
        createdField = new javax.swing.JTextField();
        type_req = new javax.swing.JLabel();
        fieldType = new javax.swing.JTextField();
        jButtonSelectType = new javax.swing.JButton();
        method_req = new javax.swing.JLabel();
        methodField = new javax.swing.JTextField();
        jButtonSelectMethod = new javax.swing.JButton();
        Desc = new javax.swing.JLabel();
        jLabelRequired = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldTitel = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldOrganism = new javax.swing.JTextField();
        fieldManu = new javax.swing.JTextField();
        fieldSupport = new javax.swing.JTextField();
        fieldCoating = new javax.swing.JTextField();
        fieldDistribution = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldTechnologie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldCatalogNr = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldWeb = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        name_req.setFont(new java.awt.Font("Dialog", 0, 12));
        name_req.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        name_req.setText("Name:");
        name_req.setName("req"); // NOI18N

        nameField.setForeground(new java.awt.Color(0, 0, 0));
        nameField.setMaximumSize(new java.awt.Dimension(20, 100));
        nameField.setMinimumSize(new java.awt.Dimension(4, 50));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.name}"), nameField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText("ID:");

        fieldID.setEditable(false);
        fieldID.setPreferredSize(new java.awt.Dimension(200, 19));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.platformID}"), fieldID, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.description}"), jTextArea1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTextArea1);

        modifiedField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.modified}"), modifiedField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(new Converter<Date, String>() {
            @Override
            public String convertForward(Date value) {
                return DateFormat.getDateInstance().format(value);
            }

            @Override
            public Date convertReverse(String value) {

                try {
                    return DateFormat.getDateInstance().parse(value);
                } catch (ParseException e) {
                    return Calendar.getInstance().getTime();
                }
            }
        }
    );
    bindingGroup.addBinding(binding);

    createdField.setEditable(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.created}"), createdField, org.jdesktop.beansbinding.BeanProperty.create("text"));
    binding.setConverter(new Converter<Date, String>() {
        @Override
        public String convertForward(Date value) {
            return DateFormat.getDateInstance().format(value);
        }

        @Override
        public Date convertReverse(String value) {

            try {
                return DateFormat.getDateInstance().parse(value);
            } catch (ParseException e) {
                return Calendar.getInstance().getTime();
            }
        }
    }
    );
    bindingGroup.addBinding(binding);

    type_req.setFont(new java.awt.Font("Dialog", 0, 12));
    type_req.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    type_req.setText("Type:");
    type_req.setMinimumSize(null);
    type_req.setName("req"); // NOI18N

    fieldType.setToolTipText("Oligo, BAC, ...");
    fieldType.setMaximumSize(new java.awt.Dimension(20, 100));
    fieldType.setMinimumSize(new java.awt.Dimension(4, 50));
    fieldType.setPreferredSize(new java.awt.Dimension(4, 50));

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.type}"), fieldType, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jButtonSelectType.setText("select");
    jButtonSelectType.setMargin(new java.awt.Insets(2, 1, 2, 1));
    jButtonSelectType.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSelectTypeActionPerformed(evt);
        }
    });

    method_req.setFont(new java.awt.Font("Dialog", 0, 12));
    method_req.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    method_req.setText("Method:");
    method_req.setMinimumSize(null);
    method_req.setName("req"); // NOI18N

    methodField.setMaximumSize(new java.awt.Dimension(20, 100));
    methodField.setMinimumSize(new java.awt.Dimension(4, 50));
    methodField.setPreferredSize(new java.awt.Dimension(4, 50));

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.method}"), methodField, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jButtonSelectMethod.setText("select");
    jButtonSelectMethod.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButtonSelectMethod.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSelectMethodActionPerformed(evt);
        }
    });

    Desc.setFont(new java.awt.Font("Dialog", 0, 12));
    Desc.setText("Description:");

    jLabelRequired.setFont(new java.awt.Font("Dialog", 2, 10));
    jLabelRequired.setText("* required fields");

    jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel3.setText("Title:");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.titel}"), fieldTitel, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(name_req, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(Desc, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(method_req, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(type_req, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(createdField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(modifiedField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addComponent(fieldID, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addComponent(jLabelRequired)
                .addComponent(fieldTitel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fieldType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(methodField, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonSelectMethod, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonSelectType, javax.swing.GroupLayout.Alignment.TRAILING))))
            .addContainerGap())
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonSelectMethod, jButtonSelectType});

    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel1)
                .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(name_req)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel3)
                .addComponent(fieldTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(createdField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(modifiedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Desc)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(12, 12, 12)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(method_req, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(methodField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSelectMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(type_req, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSelectType, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
            .addComponent(jLabelRequired))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel2.setText("manufacturer:");

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel4.setText("protocol:");

    jLabel5.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel5.setText("support:");

    jLabel6.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel6.setText("coating:");

    jLabel8.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel8.setText("distribution:");

    jLabel9.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel9.setText("organism:");

    fieldOrganism.setToolTipText("<html>standard NCBI Taxonomy nomenclature<br/>Identify the organism(s) from which the features <br/>on the Platform were designed or derived</html>");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.organism}"), fieldOrganism, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    fieldManu.setToolTipText("Provide the name of the company, facility or laboratory where the array was manufactured or produced.");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.manufacturer}"), fieldManu, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    fieldSupport.setToolTipText("Provide the surface type of the array, e.g., glass, nitrocellulose, nylon, silicon, unknown.");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.support}"), fieldSupport, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    fieldCoating.setToolTipText("Provide the coating of the array, e.g., aminosilane, quartz, polysine, unknown.'");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.coating}"), fieldCoating, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.distribution}"), fieldDistribution, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jLabel10.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel10.setText("technology:");

    fieldTechnologie.setToolTipText("spotted DNA/cDNA, spotted oligonucleotide, in situ oligonucleotide, antibody, tissue, SARST, RT-PCR, or MPSS");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.technology}"), fieldTechnologie, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jLabel11.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel11.setText("catalognumber:");

    fieldCatalogNr.setToolTipText("Provide the manufacturer catalog number for commercially-available arrays");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.catalogNumber}"), fieldCatalogNr, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jTextArea2.setColumns(20);
    jTextArea2.setRows(5);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.manufactureProtocol}"), jTextArea2, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jScrollPane2.setViewportView(jTextArea2);

    jLabel7.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel7.setText("Weblink:");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${platform.webLink}"), jTextFieldWeb, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldTechnologie, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(fieldOrganism, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(fieldManu, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(fieldCatalogNr, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fieldSupport, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fieldCoating, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fieldDistribution, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldWeb, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(fieldTechnologie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel9)
                .addComponent(fieldOrganism, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel2)
                .addComponent(fieldManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(fieldCatalogNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel5)
                .addComponent(fieldSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel6)
                .addComponent(fieldCoating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel8)
                .addComponent(fieldDistribution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jTextFieldWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(26, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

    bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonSelectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectTypeActionPerformed
    final JPanel panel = new JPanel();
    Vector<String> possibilities = DBUtils.getAllArrayTypes();
    final JComboBox combo = new JComboBox(possibilities);
    combo.setEditable(true);
    panel.add(combo);
    if (JOptionPane.showConfirmDialog(null, panel,
            "choose method", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
        this.fieldType.setText((String) combo.getSelectedItem());
    }
}//GEN-LAST:event_jButtonSelectTypeActionPerformed

private void jButtonSelectMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectMethodActionPerformed
    final JPanel panel = new JPanel();
    Vector<String> possibilities = DBUtils.getAllArrayMethods();
    final JComboBox combo = new JComboBox(possibilities);
    combo.setEditable(true);
    panel.add(combo);
    if (JOptionPane.showConfirmDialog(null, panel,
            "choose method", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
        this.methodField.setText((String) combo.getSelectedItem());
    }
}//GEN-LAST:event_jButtonSelectMethodActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desc;
    private javax.swing.JTextField createdField;
    private javax.swing.JTextField fieldCatalogNr;
    private javax.swing.JTextField fieldCoating;
    private javax.swing.JTextField fieldDistribution;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldManu;
    private javax.swing.JTextField fieldOrganism;
    private javax.swing.JTextField fieldSupport;
    private javax.swing.JTextField fieldTechnologie;
    private javax.swing.JTextField fieldTitel;
    private javax.swing.JTextField fieldType;
    private javax.swing.JButton jButtonSelectMethod;
    private javax.swing.JButton jButtonSelectType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRequired;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldWeb;
    private javax.swing.JTextField methodField;
    private javax.swing.JLabel method_req;
    private javax.swing.JTextField modifiedField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel name_req;
    private javax.swing.JLabel type_req;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void setAllFieldsEditable(boolean b) {

        List<javax.swing.JComponent> list = SwingUtils.getDescendantsOfType(javax.swing.JComponent.class, this);
        for (javax.swing.JComponent field : list) {
            if (field instanceof javax.swing.text.JTextComponent) {
                ((javax.swing.text.JTextComponent) field).setEditable(b);
                continue;
            }
            if (field instanceof javax.swing.JComboBox) {
                ((javax.swing.JComboBox) field).setEditable(b);
                continue;
            }
            if (field instanceof javax.swing.JButton) {
                ((javax.swing.JButton) field).setEnabled(b);
                continue;
            }
            if (field instanceof javax.swing.JLabel) {
                if (field.getName() != null && field.getName().indexOf("req") >= 0) {
                    if (b) {
                        ((javax.swing.JLabel) field).setText(((javax.swing.JLabel) field).getText().replace(":", "*:"));
                    } else {
                        ((javax.swing.JLabel) field).setText(((javax.swing.JLabel) field).getText().replace("*:", ":"));
                    }

                }
                continue;
            }

        }

        this.jLabelRequired.setVisible(b);

        //never editable...
        this.modifiedField.setEditable(false);
        this.createdField.setEditable(false);
        this.fieldID.setEditable(false);

    }
}
